codecov:
  disable_default_path_fixes: true
coverage:
  range: "0...100"
  status:
    patch:
      default:
        informational: true
    project:
      default:
        informational: true
fixes:
  - "::src-tauri/" # eg. remaps `src/main.rs` to `src-tauri/src/main.rs`
