os:
- windows
- linux
- osx
dist: xenial

language: rust
rust:
- nightly

before_install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update ; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install libgtk-3-dev ; fi

install: cargo build --release --verbose

script: cargo test --release --verbose

before_deploy:
  - mkdir artifacts
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then cp target/release/tiger.exe artifacts ; fi


deploy:
  provider: releases
  skip_cleanup: true
  draft: true
  api_key:
    secure: "YoVPvXlf1FXMhcBebe9FL/fyZPMb62nFVNoVHQ6SSyq22LSD+EPgKDIvGyFMVk6MXyzgVTIJD1IkjiHYK94kuXPQxNiOXIUg1n/GTa6BTqdmZY9mnPJz5sfv4aFZqD7zbkgG4hJocohS9zQYdqdgnStiRVpM93jo1Ku1NrNd2YxVGGkVu9N8CvYKKeYFuwmdpLxSCI0CNtT2gjFkrl63ikD81v1d3h7Oudhm0yyzFngJN+vuxhplhSfOfaEjWfxg0H0tGKC8ghkTfnx66rSjNE0pMLlxB4+YRh6Pq550Dl4x8DfRfbFiRK7BLT9a3CowSGp/1aTCvfpkCynRJST8ubDYysz99eHCax3Gz41n4q4A1PD76y4zzqzwsLkCTQ3MMjKN9ZdHpPBmi4/GHIh4qJ9xc3R/lMD/4L1hWXrvm80OVLc4uX2kp6PBApPIBW3vCzGkhyRFXG79yPCTvVB1YogEqjqD4kukWMGfokxkqytjtu82VgpF8/elMLpRZ1XJiozkQBW0JgULoqTsp+q4SZBc82FMBx6x5yCZB2rZLDeyURFF/MMzh4KPJ+5BLABDv9uQZxThu+xLPSBbxSSEaqi6E0dZp8wX1HT9AfP8kwSMPyz+HDuS16FoCYh8cu6oGKXsisWyJbKVBcdbquFkhpqoES/TJ590SeIpMTlHuXw="
  file_glob: true
  file: artifacts/*
  on:
    tags: true
