os:
  - windows
  - linux
  - osx

dist: xenial

language: rust
rust:
  - nightly

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install libgtk-3-dev ; fi

install:
  cargo build --release --verbose

script:
  cargo test --release --verbose

deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file:
    - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then target\release\tiger.exe ; fi
  skip_cleanup: true
  draft: true
  on:
    tags: true
