[package]
name = "tiger"
version = "0.1.0"
authors = ["Antoine Gersant <antoine.gersant@lesforges.org>"]

[dependencies]
failure = "0.1.3"
imgui = { git = "https://github.com/Gekkio/imgui-rs" }
imgui-glium-renderer = { git = "https://github.com/Gekkio/imgui-rs" }
imgui-glutin-support = { git = "https://github.com/Gekkio/imgui-rs" }
nfd = "0.0.4"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"

[dependencies.glium]
version = "0.22.0"
default-features = true
features = ["icon_loading"]
