[package]
name = "tiger"
version = "0.1.0"
authors = ["Antoine Gersant <antoine.gersant@lesforges.org>"]

[dependencies]
failure = "0.1.3"
glium = "0.22.0"
imgui = { git = "https://github.com/Gekkio/imgui-rs" }
imgui-glium-renderer = { git = "https://github.com/Gekkio/imgui-rs" }
imgui-glutin-support = { git = "https://github.com/Gekkio/imgui-rs" }