[package]
name = "tiger"
version = "0.1.0"
authors = ["Antoine Gersant <antoine.gersant@lesforges.org>"]
edition = "2018"

[dependencies]
dunce = "0.1.1"
euclid = { git = "https://github.com/servo/euclid", rev="650b129" }
failure = "0.1.3"
gfx = "0.18"
gfx_core = "0.9.0"
gfx_device_gl = "0.16"
gfx_window_glutin = "0.30"
image = "0.20"
imgui = { path = "../imgui-rs" }
imgui-gfx-renderer = { path = "../imgui-rs/imgui-gfx-renderer" }
imgui-winit-support = { path = "../imgui-rs/imgui-winit-support" }
liquid = "0.17"
nfd = "0.0.4"
pathdiff = "0.1.0"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
texture_packer = "0.15"

[dependencies.glutin]
version = "0.20.0"
features = [ "icon_loading" ]
