[package]
name = "tiger"
version = "0.1.0"
authors = ["Antoine Gersant <antoine.gersant@lesforges.org>"]
edition = "2018"

[dependencies]
dunce = "0.1.1"
failure = "0.1.3"
gfx = { git = "https://github.com/gfx-rs/gfx", branch="pre-ll" }
gfx_core = { git = "https://github.com/gfx-rs/gfx", branch="pre-ll" }
gfx_device_gl = { git = "https://github.com/gfx-rs/gfx", branch="pre-ll" }
gfx_window_glutin = { git = "https://github.com/gfx-rs/gfx", branch="pre-ll" }
image = "0.20"
# TODO imgui master now has glutin19, still needs content regions and hover flags to get rid of fork
imgui = { git = "https://github.com/agersant/imgui-rs", branch = "tiger" }
imgui-gfx-renderer = { git = "https://github.com/agersant/imgui-rs", branch = "tiger" }
imgui-glutin-support = { git = "https://github.com/agersant/imgui-rs", branch = "tiger" }
liquid = "0.17"
nfd = "0.0.4"
pathdiff = "0.1.0"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
texture_packer = "0.15"

[dependencies.glutin]
version = "0.19.0"
features = [ "icon_loading" ]

[replace]
"gfx:0.17.1" = { git = 'https://github.com/gfx-rs/gfx', branch = 'pre-ll' }