name: Build

on:
  pull_request:
  push:
    branches:
      - master
      - 0.3

jobs:
  test:
    name: Run Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        default: true
    - uses: actions-rs/cargo@v1
      with:
        command: test
        args: --release
