name: CI Tests

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Run Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Install libgtk-3-dev
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install libgtk-3-dev
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release
