name: CI Tests

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Run Tests
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
      - name: cargo test
        working-directory: ./src-tauri
        run: cargo test --release
