name: Test Coverage

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Measure Test Coverage
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly # https://github.com/actions-rs/grcov#usage
          profile: minimal
          default: true
      - name: Download Build Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            src-tauri/target/
          key: ${{ runner.os }}-cargo-${{ github.ref }}-${{ github.sha }}
          restore-keys: ${{ runner.os }}-cargo-${{ github.ref }}
      - name: Install grcov
        run: cargo install grcov
      - name: Install Tauri Dependencies
        run: sudo apt update && sudo apt install libwebkit2gtk-4.0-dev build-essential curl wget libssl-dev libgtk-3-dev libappindicator3-dev librsvg2-dev
      - name: Build Frontend
        run: npm install && npm run build
      - name: Run Tests
        run: cargo test --no-fail-fast
        working-directory: src-tauri
        env:
          CARGO_INCREMENTAL: "0"
          RUSTFLAGS: "-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests"
      - name: Gather Results
        run: grcov ./target/debug -s . --llvm --branch --guess-directory-when-missing --ignore-not-existing -t lcov -o coverage.txt
        working-directory: src-tauri
      - name: Upload Results
        uses: codecov/codecov-action@v2
        with:
          file: src-tauri/coverage.txt
          fail_ci_if_error: true
