name: Test Coverage

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Measure Test Coverage
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          default: true
      - uses: actions/cache@v3
        with:
          path: src-tauri/target/
          key: ${{ runner.os }}-cargo-${{ github.ref }}-${{ github.sha }}
          restore-keys: ${{ runner.os }}-cargo-${{ github.ref }}
      - name: Install Tauri Dependencies
        run: sudo apt update && sudo apt install libwebkit2gtk-4.0-dev build-essential curl wget libssl-dev libgtk-3-dev libappindicator3-dev librsvg2-dev
      - name: Build Frontend
        run: npm install && npm run build
      - name: Run Tarpaulin
        uses: actions-rs/tarpaulin@v0.1
        with:
          args: "--root src-tauri --ignore-tests"
      - name: Upload Results
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
