on:
  workflow_dispatch:
    inputs:
      versionNumber:
        description: "User-facing version number (eg: 0.3.0)"
        required: true

name: Make Release

jobs:
  setup_release:
    name: Setup Release
    runs-on: ubuntu-latest
    outputs:
      RELEASE_ID: ${{ steps.create-release.outputs.id }}

    steps:
      - name: Merge to Release Branch
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          target_branch: release
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Github Release
        id: create-release
        uses: softprops/action-gh-release@v1
        with:
          name: Tiger ${{ github.event.inputs.versionNumber }}
          tag_name: ${{ github.event.inputs.versionNumber }}
          target_commitish: release
          draft: true

  build_windows_binaries:
    name: Build Windows Binaries
    runs-on: windows-latest
    needs: setup_release

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: release
      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          default: true
      - name: Install frontend dependencies
        run: npm install
      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          releaseId: ${{ needs.create-release.outputs.RELEASE_ID }}
          args: >
            --config '{ \"package\": { \"version\": \"${{ github.event.inputs.versionNumber }}\" } }'
